using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using OrcaJournal.Data;
using OrcaJournal.Data.Models;
using OrcaJournal.UI.Windows;
class Program
{
    static IEnumerable<T> Find<T>(DependencyObject root) where T:DependencyObject {
        for(int i=0;i<VisualTreeHelper.GetChildrenCount(root);i++) {var c=VisualTreeHelper.GetChild(root,i);if(c is T)yield return (T)c;foreach(var v in Find<T>(c))yield return v;}
    }
    [STAThread] static int Main(string[] args) {
        try {
            var app=new Application { ShutdownMode=ShutdownMode.OnExplicitShutdown };
            using(var db=new DatabaseManager(Path.Combine(args[0],"fixture.db"))) {
                db.Initialize();var repo=new TradeRepository(db);var t=new Trade{TradeKey="ui",Account="SIM",Instrument="MES",InstrumentFullName="MES SEP26",Direction="Long",SessionDate="2026-09-05",EntryTime=DateTime.Today,ExitTime=DateTime.Today.AddMinutes(1),Quantity=1,PnlDollars=275,Notes="Waited for a pullback. Review the entry timing.",SetupGrade="B"};repo.Insert(t);
                var tagRepo=new TagRepository(db);
                foreach(var name in new[]{"FVG","iFVG","MGI","node","OB","Passive Player","RB","Structure","Sweep","TAPER"})tagRepo.GetOrCreateTag(name,"#4285F4");
                int saves=0;var window=new TradeReviewWindow(new TradeReviewRepository(db),t.Id,"SIM · MES · Long",()=>saves++);
                window.WindowStartupLocation=WindowStartupLocation.Manual;window.Left=-20000;window.Top=-20000;window.ShowActivated=false;window.ShowInTaskbar=false;window.Show();
                var root=(FrameworkElement)window.Content; root.Measure(new Size(680,740));root.Arrange(new Rect(0,0,680,740));root.UpdateLayout();
                var boxes=Find<TextBox>(root).Where(x=>!x.IsReadOnly && x.AcceptsReturn).ToList();
                if(boxes.Count!=1)throw new Exception("Expected notes editor and checkbox tags");
                Find<TextBox>(root).Single(x=>x.Name=="PlannedRisk").Text="200";
                boxes[0].Text="Waited for confirmation; next time review stop placement before entering.";Find<CheckBox>(root).Single(x=>x.Content as string=="Risked proper amount").IsChecked=true; Find<CheckBox>(root).Single(x=>x.Content as string=="Took proper partials").IsChecked=true;
                Find<ComboBox>(root).First().SelectedItem="A-";
                if(!Find<TextBlock>(root).Any(x=>x.Text.StartsWith("Unsaved changes")))throw new Exception("Missing dirty feedback");
                Find<Button>(root).Single(x=>x.Content as string=="Save review").RaiseEvent(new RoutedEventArgs(Button.ClickEvent));root.UpdateLayout();
                if(new TradeReviewRepository(db).Read(t.Id).PlannedRisk!=200)throw new Exception("Risk save failed");
                if(saves!=1 || new TradeReviewRepository(db).Read(t.Id).Grade!="A-")throw new Exception("Save integration failed");
                if(!Find<TextBlock>(root).Any(x=>x.Text=="Saved."))throw new Exception("Missing saved feedback");
                var frame=new System.Windows.Threading.DispatcherFrame();
                System.Windows.Threading.Dispatcher.CurrentDispatcher.BeginInvoke(System.Windows.Threading.DispatcherPriority.ApplicationIdle,new Action(()=>frame.Continue=false));
                System.Windows.Threading.Dispatcher.PushFrame(frame);
                var bitmap=new RenderTargetBitmap(680,740,96,96,PixelFormats.Pbgra32);bitmap.Render(root);var encoder=new PngBitmapEncoder();encoder.Frames.Add(BitmapFrame.Create(bitmap));using(var f=File.Create(Path.Combine(args[0],"review.png")))encoder.Save(f);
                boxes[0].Text="My unsaved draft";
                var raw=repo.GetById(t.Id);raw.Notes="A later chart edit";repo.Update(raw);
                Find<Button>(root).Single(x=>x.Content as string=="Save review").RaiseEvent(new RoutedEventArgs(Button.ClickEvent));root.UpdateLayout();
                if(boxes[0].Text!="My unsaved draft")throw new Exception("Conflict lost draft");
                var keep=Find<Button>(root).Single(x=>x.Content as string=="Keep my changes");
                if(((FrameworkElement)((FrameworkElement)keep.Parent).Parent).Visibility!=Visibility.Visible)throw new Exception("Conflict choices not exposed");
                keep.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));root.UpdateLayout();
                if(saves!=2 || new TradeReviewRepository(db).Read(t.Id).Notes!="My unsaved draft" || repo.GetById(t.Id).Notes!="A later chart edit")throw new Exception("Explicit resolution failed");
                window.Close();
                var mediaRepo=new AttachmentRepository(db);var attachment=new TradeAttachment{TradeId=t.Id,FilePath=Path.Combine(args[0],"example.png"),Kind="image",CreatedAt=DateTime.Now};mediaRepo.Insert(attachment);
                var mediaWindow=new TradeMediaWindow(mediaRepo,t.Id,()=>{});
                mediaWindow.WindowStartupLocation=WindowStartupLocation.Manual;mediaWindow.Left=-20000;mediaWindow.Top=-20000;mediaWindow.ShowActivated=false;mediaWindow.ShowInTaskbar=false;mediaWindow.Show();
                var mediaRoot=(FrameworkElement)mediaWindow.Content;mediaRoot.UpdateLayout();
                Find<TextBox>(mediaRoot).Single().Text="Entry setup";mediaWindow.Close();
                if(mediaRepo.GetForTrade(t.Id).Single().Caption!="Entry setup")throw new Exception("Caption not saved on close");
                var imagePath=Path.Combine(args[0],"review.png");
                var imageMedia=new TradeAttachment {FilePath=imagePath,Kind="image",Caption="Entry setup"};
                var thumbnail=(BitmapSource)new OrcaJournal.UI.Controls.AttachmentThumbnailConverter().Convert(imageMedia,typeof(BitmapSource),null,System.Globalization.CultureInfo.InvariantCulture);
                if(thumbnail==null || !thumbnail.IsFrozen)throw new Exception("Thumbnail decode failed");
                using(var exclusive=new FileStream(imagePath,FileMode.Open,FileAccess.ReadWrite,FileShare.None)) {}
                var moved=imagePath+".renamed";File.Move(imagePath,moved);File.Move(moved,imagePath);
                if(thumbnail.PixelWidth!=256)throw new Exception("Thumbnail size unbounded");
                mediaRepo.Insert(new TradeAttachment{TradeId=t.Id,FilePath=imagePath,Kind="image",Caption="Chart context",CreatedAt=DateTime.Now});
                mediaRepo.Insert(new TradeAttachment{TradeId=t.Id,FilePath=Path.Combine(args[0],"recording.mp4"),Kind="video",Caption="Recorded trade",CreatedAt=DateTime.Now});
                var mediaReview=new TradeReviewWindow(new TradeReviewRepository(db),t.Id,"test",()=>{});
                mediaReview.Left=-20000;mediaReview.Top=-20000;mediaReview.ShowActivated=false;mediaReview.ShowInTaskbar=false;mediaReview.Show();mediaReview.UpdateLayout();
                if(!Find<Button>(mediaReview).Any(x=>x.Content as string=="Open screenshot"))throw new Exception("Review missing screenshot action");
                if(!Find<TextBlock>(mediaReview).Any(x=>x.Text=="Entry setup"))throw new Exception("Review missing media title");
                if(!Find<Button>(mediaReview).Any(x=>x.Content as string=="Play video"))throw new Exception("Review missing video action");
                if(!Find<Image>(mediaReview).Any(x=>x.Source!=null))throw new Exception("Review thumbnail failed");
                ((ScrollViewer)mediaReview.Content).ScrollToBottom();mediaReview.UpdateLayout();
                var mediaBitmap=new RenderTargetBitmap(700,780,96,96,PixelFormats.Pbgra32);mediaBitmap.Render((Visual)mediaReview.Content);var mediaEncoder=new PngBitmapEncoder();mediaEncoder.Frames.Add(BitmapFrame.Create(mediaBitmap));using(var file=File.Create(Path.Combine(args[0],"review-media.png")))mediaEncoder.Save(file);
                mediaReview.Close();
                var library=new OrcaJournal.UI.Views.TagLibraryView(db);
                var libraryWindow=new Window{Content=library,Width=1200,Height=800,Left=-20000,Top=-20000,ShowActivated=false,ShowInTaskbar=false};libraryWindow.Show();library.UpdateLayout();
                if(Find<Expander>(library).Single().IsExpanded)throw new Exception("Advanced should start collapsed");
                Find<Button>(library).Single(x=>x.Tag as string=="Risked proper amount").RaiseEvent(new RoutedEventArgs(Button.ClickEvent));library.UpdateLayout();
                if(!Find<TextBlock>(library).Any(x=>x.Name=="LibraryStatus" && x.Text.StartsWith("1 trades")) || !Find<Image>(library).Any(x=>x.Source!=null) || !Find<Button>(library).Any(x=>x.Content as string=="Play video"))throw new Exception("Library effective tag membership/media failed");
                var libraryBitmap=new RenderTargetBitmap(1200,800,96,96,PixelFormats.Pbgra32);libraryBitmap.Render(library);var libraryEncoder=new PngBitmapEncoder();libraryEncoder.Frames.Add(BitmapFrame.Create(libraryBitmap));using(var file=File.Create(Path.Combine(args[0],"tag-library.png")))libraryEncoder.Save(file);
                new TradeReviewRepository(db).SaveTagGroup("Risked proper amount",ReviewTagOption.Analysis);
                library.Reload();if(new TradeReviewRepository(db).TagOptions("").Single(x=>x.Name=="Risked proper amount").Category!=ReviewTagOption.Analysis || new TradeReviewRepository(db).Read(t.Id).Notes!="My unsaved draft")throw new Exception("Grouping changed review or failed");
                Find<Button>(library).Single(x=>x.Tag as string=="Sweep").RaiseEvent(new RoutedEventArgs(Button.ClickEvent));library.UpdateLayout();if(!Find<TextBlock>(library).Any(x=>x.Text.StartsWith("No trades have this tag")))throw new Exception("Unused-tag empty state failed");
                for(int i=0;i<20;i++)mediaRepo.Insert(new TradeAttachment{TradeId=t.Id,FilePath=Path.Combine(args[0],"missing"+i+".png"),Kind="image",Caption="Page "+i,CreatedAt=DateTime.Now});
                var detached=new TradeAttachment{TradeId=t.Id,FilePath="detached.png",Kind="image"};mediaRepo.Insert(detached);mediaRepo.Detach(t.Id,detached.Id);
                library.Reload();Find<Button>(library).Single(x=>x.Tag as string=="Risked proper amount").RaiseEvent(new RoutedEventArgs(Button.ClickEvent));library.UpdateLayout();
                if(Find<Button>(library).Count(x=>x.Content as string=="Open full review")!=18 || !Find<TextBlock>(library).Any(x=>x.Name=="LibraryStatus" && x.Text.Contains("23 media")))throw new Exception("Gallery paging or detached exclusion failed");
                Find<Button>(library).Single(x=>x.Content as string=="Next").RaiseEvent(new RoutedEventArgs(Button.ClickEvent));library.UpdateLayout();if(Find<Button>(library).Count(x=>x.Content as string=="Open full review")!=5)throw new Exception("Gallery next page failed");
                var libraryRepo=new TradeReviewRepository(db);var beforeRemoval=libraryRepo.Read(t.Id);
                libraryRepo.RemoveTagFromLibrary("Risked proper amount");library.Reload();library.UpdateLayout();
                if(Find<Button>(library).Any(x=>x.Tag as string=="Risked proper amount") || libraryRepo.Read(t.Id).Tags!=beforeRemoval.Tags || libraryRepo.Read(t.Id).Revision!=beforeRemoval.Revision || !libraryRepo.TagOptions(beforeRemoval.Tags).Any(x=>x.Name=="Risked proper amount"))throw new Exception("Removal must hide picker but preserve historical assignments");
                if(libraryRepo.TagOptions("").Any(x=>x.Name=="Risked proper amount"))throw new Exception("Removed tag offered for new assignment");
                libraryRepo.SaveTagGroup("Risked proper amount",ReviewTagOption.Management);library.Reload();library.UpdateLayout();if(!Find<Button>(library).Any(x=>x.Tag as string=="Risked proper amount"))throw new Exception("Restore tag failed");
                libraryWindow.Close();Console.WriteLine("PASS: Tag Library effective tags, groups, media and empty state; advanced collapsed.");
                var dayVm=new OrcaJournal.UI.ViewModels.TradesViewModel();dayVm.Load(repo.GetAll(),tagRepo,mediaRepo,new[]{"All Accounts","SIM"});
                dayVm.FilterDirection="Short";dayVm.FilterInstrument="NQ";dayVm.ShowDay(new DateTime(2026,9,5),"SIM");
                if(dayVm.Trades.Count!=1 || dayVm.SelectedTrade.Id!=t.Id || dayVm.FilterInstrument!="All" || dayVm.FilterDirection!="All")throw new Exception("Day navigation scope failed");
                dayVm.ShowDay(new DateTime(2000,1,1),"SIM");if(dayVm.Trades.Count!=0 || dayVm.SelectedTrade!=null)throw new Exception("Empty day retained selected trade");
                var outcomeVm=new OrcaJournal.UI.ViewModels.TradesViewModel();
                var outcomeTrades=new[]{new Trade{Id=1001,SessionDate="2026-09-06",PnlDollars=-100,Instrument="MES",Direction="Short"},new Trade{Id=1002,SessionDate="2026-09-06",PnlDollars=4,Instrument="MNQ",Direction="Long"},new Trade{Id=1003,SessionDate="2026-09-06",PnlDollars=200,Instrument="MES",Direction="Long"}};
                outcomeVm.Load(outcomeTrades,null,null,new[]{"All Accounts"});outcomeVm.ShowDay(new DateTime(2026,9,6),"All Accounts");
                outcomeVm.OutcomeBucket="Exclude breakevens";if(outcomeVm.Trades.Count!=2)throw new Exception("Outcome filter failed");
                outcomeVm.OutcomeBucket="All trades";
                var outcomeView=new OrcaJournal.UI.Views.TradesView{DataContext=outcomeVm};var outcomeWindow=new Window{Content=outcomeView,Width=1200,Height=700,Left=-20000,Top=-20000,ShowActivated=false,ShowInTaskbar=false};outcomeWindow.Show();outcomeView.UpdateLayout();
                var outcomeGrid=Find<DataGrid>(outcomeView).Single();
                var header=Find<System.Windows.Controls.Primitives.DataGridColumnHeader>(outcomeGrid).Single(x=>x.Column!=null && x.Column.SortMemberPath=="PnlDollars");
                var click=typeof(System.Windows.Controls.Primitives.DataGridColumnHeader).GetMethod("OnClick",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic);
                click.Invoke(header,null);if(((Trade)outcomeGrid.Items[0]).PnlDollars!=-100)throw new Exception("Ascending P&L header sort failed");
                click.Invoke(header,null);if(((Trade)outcomeGrid.Items[0]).PnlDollars!=200)throw new Exception("Descending P&L header sort failed");
                outcomeGrid.SelectedItem=null;outcomeGrid.UpdateLayout();
                var lossRow=(DataGridRow)outcomeGrid.ItemContainerGenerator.ContainerFromItem(outcomeTrades[0]);var winRow=(DataGridRow)outcomeGrid.ItemContainerGenerator.ContainerFromItem(outcomeTrades[2]);
                if(lossRow.Background.ToString()==winRow.Background.ToString())throw new Exception("Outcome row colors missing");
                var outcomeBitmap=new RenderTargetBitmap(1200,700,96,96,PixelFormats.Pbgra32);outcomeBitmap.Render(outcomeView);var outcomeEncoder=new PngBitmapEncoder();outcomeEncoder.Frames.Add(BitmapFrame.Create(outcomeBitmap));using(var file=File.Create(Path.Combine(args[0],"outcomes.png")))outcomeEncoder.Save(file);
                outcomeWindow.Close();
                var performance=new OrcaJournal.UI.Views.TagPerformanceView(db);
                var performanceWindow=new Window{Content=performance,Width=1200,Height=720,Left=-20000,Top=-20000,ShowActivated=false,ShowInTaskbar=false};performanceWindow.Show();performance.UpdateLayout();
                var checks=Find<CheckBox>(performance).ToList();
                checks.Single(x=>x.Tag as string=="Risked proper amount").IsChecked=true;
                checks.Single(x=>x.Tag as string=="Took proper partials").IsChecked=true;
                var performanceSummary=Find<TextBlock>(performance).Single(x=>x.Name=="TagSummary");
                if(!performanceSummary.Text.StartsWith("1 / 1"))throw new Exception("Tag intersection UI failed");
                Find<ComboBox>(performance).Single(x=>x.Name=="TagMatchMode").SelectedIndex=1;
                if(!performanceSummary.Text.StartsWith("1 / 1"))throw new Exception("Tag union duplicated trade");
                Find<DatePicker>(performance).Single(x=>x.Name=="TagFrom").SelectedDate=new DateTime(2027,1,1);
                if(!performanceSummary.Text.StartsWith("0 / 0"))throw new Exception("Tag date scope failed");
                Find<DatePicker>(performance).Single(x=>x.Name=="TagFrom").SelectedDate=null;
                performance.Reload();performance.UpdateLayout();
                if(Find<CheckBox>(performance).Count(x=>x.IsChecked==true)!=2)throw new Exception("Refresh lost selected tags");
                Find<TextBox>(performance).Single(x=>x.Name=="SavedTagViewName").Text="Managed setup";
                Find<Button>(performance).Single(x=>x.Content as string=="Save new").RaiseEvent(new RoutedEventArgs(Button.ClickEvent));
                Find<Button>(performance).Single(x=>x.Content as string=="Clear tags").RaiseEvent(new RoutedEventArgs(Button.ClickEvent));
                Find<ComboBox>(performance).Single(x=>x.Name=="TagMatchMode").SelectedIndex=0;
                Find<DatePicker>(performance).Single(x=>x.Name=="TagFrom").SelectedDate=new DateTime(2027,1,1);
                Find<Button>(performance).Single(x=>x.Content as string=="Load").RaiseEvent(new RoutedEventArgs(Button.ClickEvent));
                performance.UpdateLayout();
                if(Find<CheckBox>(performance).Count(x=>x.IsChecked==true)!=2 || Find<ComboBox>(performance).Single(x=>x.Name=="TagMatchMode").SelectedIndex!=1 || Find<DatePicker>(performance).Single(x=>x.Name=="TagFrom").SelectedDate!=new DateTime(2027,1,1))throw new Exception("Saved combination did not restore tags and mode while keeping dates");
                Find<DatePicker>(performance).Single(x=>x.Name=="TagFrom").SelectedDate=null;
                Console.WriteLine("PASS: saved-combination UI saves and restores tags/match while preserving date scope.");
                var tagFrame=new System.Windows.Threading.DispatcherFrame();System.Windows.Threading.Dispatcher.CurrentDispatcher.BeginInvoke(System.Windows.Threading.DispatcherPriority.ApplicationIdle,new Action(()=>tagFrame.Continue=false));System.Windows.Threading.Dispatcher.PushFrame(tagFrame);
                var tagBitmap=new RenderTargetBitmap(1200,720,96,96,PixelFormats.Pbgra32);tagBitmap.Render(performance);var tagEncoder=new PngBitmapEncoder();tagEncoder.Frames.Add(BitmapFrame.Create(tagBitmap));using(var file=File.Create(Path.Combine(args[0],"tag-performance.png")))tagEncoder.Save(file);
                var baselineTab=Find<TabItem>(performance).Single(x=>x.Header as string=="Compared with all trades");baselineTab.IsSelected=true;performance.UpdateLayout();
                var baselineGrid=Find<DataGrid>(performance).Single(x=>x.Name=="TagBaseline");
                var baselineRows=baselineGrid.ItemsSource.Cast<OrcaJournal.Analytics.TagPerformanceStats>().ToList();
                if(baselineRows.Count!=2 || baselineRows[0].Count!=1 || baselineRows[1].Count!=1 || baselineRows[0].Average!=275 || baselineRows[1].Average!=275)throw new Exception("Baseline comparison scope failed");
                Find<DatePicker>(performance).Single(x=>x.Name=="TagFrom").SelectedDate=new DateTime(2027,1,1);
                if(baselineGrid.ItemsSource.Cast<OrcaJournal.Analytics.TagPerformanceStats>().Any(x=>x.Count!=0 || x.Average.HasValue))throw new Exception("Empty baseline not unknown");
                performanceWindow.Close();
                Console.WriteLine("PASS: tag-performance UI intersection, union, dates and refresh selections.");
                Console.WriteLine("PASS: actual WPF thumbnail permits exclusive reopen and rename while bitmap remains alive.");
                Console.WriteLine("PASS: review editor loads theme, edits notes/tags/grade, saves, refreshes, and shows save feedback.");
            }
            return 0;
        } catch(Exception ex){Console.Error.WriteLine(ex);return 1;}
    }
}
