<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="TradingPlatform.BusinessLayer">
      <HintPath>C:\Quantower\TradingPlatform\v1.145.16\bin\TradingPlatform.BusinessLayer.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
