using System.ComponentModel.DataAnnotations;
using System.Windows.Media;
using NinjaTrader.Custom;

namespace NinjaTrader.NinjaScript.Indicators;

/// <summary>
/// The Forecast Oscillator (FOSC) is an extension of the linear regression based indicators
/// made popular by Tushar Chande. The Forecast Oscillator plots the percentage difference
/// between the forecast price (generated by an x-period linear regression line) and the actual
/// price. The oscillator is above zero when the forecast price is greater than the actual price.
/// Conversely, it's less than zero if its below. In the rare case when the forecast price and the
///  actual price are the same, the oscillator would plot zero. Actual prices that are persistently
///  below the forecast price suggest lower prices ahead.  Likewise, actual prices that are persistently
///  above the forecast price suggest higher prices ahead. Short-term traders should use shorter time
///  periods and perhaps more relaxed standards for the required length of time above or below the
///  forecast price. Long-term traders should use longer time periods and perhaps stricter standards
///  for the required length of time above or below the forecast price. Chande also suggests plotting
///  a three-day moving average trigger line of the Forecast Oscillator to generate early warnings of
/// changes in trend. When the oscillator crosses below the trigger line, lower prices are suggested.
/// When the oscillator crosses above the trigger line, higher prices are suggested.
/// </summary>
public class FOSC : Indicator
{
	private TSF tsf;

	[Range(1, int.MaxValue)]
	[NinjaScriptProperty]
	[Display(ResourceType = typeof(Resource), Name = "Period", GroupName = "NinjaScriptParameters", Order = 0)]
	public int Period { get; set; }

	protected override void OnStateChange()
	{
		//IL_0001: Unknown result type (might be due to invalid IL or missing references)
		//IL_0007: Invalid comparison between Unknown and I4
		//IL_0060: Unknown result type (might be due to invalid IL or missing references)
		//IL_0066: Invalid comparison between Unknown and I4
		if ((int)((NinjaScript)this).State == 1)
		{
			((NinjaScript)this).Description = Resource.NinjaScriptIndicatorDescriptionFOSC;
			((NinjaScriptBase)this).Name = Resource.NinjaScriptIndicatorNameFOSC;
			((IndicatorBase)this).IsSuspendedWhileInactive = true;
			((NinjaScriptBase)this).IsOverlay = false;
			Period = 14;
			((NinjaScriptBase)this).AddPlot((Brush)Brushes.DarkCyan, Resource.NinjaScriptIndicatorNameFOSC);
			((NinjaScriptBase)this).AddLine((Brush)Brushes.DarkGray, 0.0, Resource.NinjaScriptIndicatorZeroLine);
		}
		else if ((int)((NinjaScript)this).State == 4)
		{
			tsf = TSF(((NinjaScriptBase)this).Inputs[0], 0, Period);
		}
	}

	protected override void OnBarUpdate()
	{
		if (!(((NinjaScriptBase)this).Input[0] <= 0.0))
		{
			((NinjaScriptBase)this).Value[0] = 100.0 * ((((NinjaScriptBase)this).Input[0] - ((NinjaScriptBase)tsf)[0]) / ((NinjaScriptBase)this).Input[0]);
		}
	}
}
